name: NPM Package

on:
  release:
    types: [published]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Tag Version
        run: ./.github/scripts/incr-version.sh ${{ github.ref_name }}

      - name: Publising to NPM
        uses: JS-DevTools/npm-publish@v3
        with:
          registry: https://registry.npmjs.org/
          token: ${{ secrets.NPM_TOKEN }}

  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Tag Version
        run: ./.github/scripts/incr-version.sh ${{ github.ref_name }}

      - name: Publising to GPR
        uses: JS-DevTools/npm-publish@v3
        with:
          registry: https://npm.pkg.github.com/
          token: ${{ secrets.GITHUB_TOKEN }}

  vdeploy:
    runs-on: ubuntu-latest
    needs: [publish-npm, publish-gpr]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Increment Version
        run: echo "bodyText=$(./.github/scripts/incr-version.sh ${{ github.ref_name }})" \
             >> $GITHUB_ENV

      - name: Version PR
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Update to ${{ github.ref_name }}
          title: Update package.json (${{ github.ref_name }})
          body: ${{ env.bodyText }}
          branch: update-version
          base: master
