name: NPM Package

on:
  release:
    types: [published]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Tag Version
        run: ./.github/scripts/incr-version.sh "$(echo $GITHUB_REF | cut -d / -f 3)"

# Deployed already
#      - name: Publising to NPM
#        uses: JS-DevTools/npm-publish@master
#        with:
#          registry: https://registry.npmjs.org/
#          token: ${{secrets.NPM_TOKEN}}

  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Tag Version
        run: ./.github/scripts/incr-version.sh "$(echo $GITHUB_REF | cut -d / -f 3)"

      - name: Publising to GPR
        uses: JS-DevTools/npm-publish@master
        with:
          registry: https://npm.pkg.github.com/
          token: ${{secrets.GHA_PACKAGES_TOKEN}}

  vdeploy:
    runs-on: ubuntu-latest
    needs: [publish-npm, publish-gpr]
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Get Tag Version
        id: new_version
        run: echo "VER=$(echo $GITHUB_REF | cut -d / -f 3)" >> $GITHUB_OUTPUT

      - name: Update Version
        id: old_version
        run: echo "VER=$(./.github/scripts/incr-version.sh ${{ steps.new_version.outputs.VER }})" \
                  >> $GITHUB_OUTPUT

      - name: Version PR
        uses: peter-evans/create-pull-request@master
        with:
          commit-message: Update to ${{ steps.new_version.outputs.VER }}
          title: Update package.json (${{ steps.new_version.outputs.VER }})
          body: ${{ steps.old_version.outputs.VER }}
          branch: update-version
          base: master
